version: "3"

services:
  web:
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 8080:8080
      - 1337:1337
    volumes:
      - data:/backend/.tmp
    ## set your startup file here
    command: npm run dev
